/**
 * Polish voivodeships (województwa) and their powiats (powiaty).
 * Based on TERYT administrative division of Poland.
 */

export interface Voivodeship {
  name: string;
  powiats: string[];
}

/**
 * Map of voivodeships to their powiats.
 * Key is the voivodeship name, value is the list of powiat names.
 */
export const VOIVODESHIPS: Record<string, Voivodeship> = {
  'Dolnośląskie': {
    name: 'Dolnośląskie',
    powiats: [
      'Wrocław',
      'Wałbrzych',
      'Legnica',
      'Jelenia Góra',
      'Bolesławiecki',
      'Dzierżoniowski',
      'Głogowski',
      'Górowski',
      'Jaworski',
      'Jeleniogórski',
      'Kamiennogórski',
      'Kłodzki',
      'Legnicki',
      'Lubański',
      'Lubiński',
      'Lwówecki',
      'Milicki',
      'Oławski',
      'Oleśnicki',
      'Polkowicki',
      'Strzeliński',
      'Średzki',
      'Świdnicki',
      'Trzebnicki',
      'Wałbrzyski',
      'Wołowski',
      'Wrocławski',
      'Ząbkowicki',
      'Zgorzelecki',
      'Złotoryjski',
    ],
  },
  'Kujawsko-Pomorskie': {
    name: 'Kujawsko-Pomorskie',
    powiats: [
      'Bydgoszcz',
      'Toruń',
      'Włocławek',
      'Grudziądz',
      'Aleksandrowski',
      'Brodnicki',
      'Bydgoski',
      'Chełmiński',
      'Golubsko-Dobrzyński',
      'Grudziądzki',
      'Inowrocławski',
      'Lipnowski',
      'Mogileński',
      'Nakielski',
      'Radziejowski',
      'Rypiński',
      'Sępoleński',
      'Świecki',
      'Tucholski',
      'Wąbrzeski',
      'Włocławski',
      'Żniński',
    ],
  },
  'Lubelskie': {
    name: 'Lubelskie',
    powiats: [
      'Lublin',
      'Biała Podlaska',
      'Chełm',
      'Zamość',
      'Bialski',
      'Biłgorajski',
      'Chełmski',
      'Hrubieszowski',
      'Janowski',
      'Krasnostawski',
      'Kraśnicki',
      'Lubartowski',
      'Lubelski',
      'Łęczyński',
      'Łukowski',
      'Opolski',
      'Parczewski',
      'Puławski',
      'Radzyński',
      'Rycki',
      'Świdnicki',
      'Tomaszowski',
      'Włodawski',
      'Zamojski',
    ],
  },
  'Lubuskie': {
    name: 'Lubuskie',
    powiats: [
      'Gorzów Wielkopolski',
      'Zielona Góra',
      'Gorzowski',
      'Krośnieński',
      'Międzyrzecki',
      'Nowosolski',
      'Słubicki',
      'Strzelecko-Drezdenecki',
      'Sulęciński',
      'Świebodziński',
      'Wschowski',
      'Zielonogórski',
      'Żagański',
      'Żarski',
    ],
  },
  'Łódzkie': {
    name: 'Łódzkie',
    powiats: [
      'Łódź',
      'Piotrków Trybunalski',
      'Skierniewice',
      'Bełchatowski',
      'Brzeziński',
      'Kutnowski',
      'Łaski',
      'Łęczycki',
      'Łowicki',
      'Łódzki Wschodni',
      'Opoczyński',
      'Pabianicki',
      'Pajęczański',
      'Piotrkowski',
      'Poddębicki',
      'Radomszczański',
      'Rawski',
      'Sieradzki',
      'Skierniewicki',
      'Tomaszowski',
      'Wieruszowski',
      'Wieluński',
      'Zduńskowolski',
      'Zgierski',
    ],
  },
  'Małopolskie': {
    name: 'Małopolskie',
    powiats: [
      'Kraków',
      'Nowy Sącz',
      'Tarnów',
      'Bocheński',
      'Brzeski',
      'Chrzanowski',
      'Dąbrowski',
      'Gorlicki',
      'Krakowski',
      'Limanowski',
      'Miechowski',
      'Myślenicki',
      'Nowosądecki',
      'Nowotarski',
      'Olkuski',
      'Oświęcimski',
      'Proszowicki',
      'Suski',
      'Tarnowski',
      'Tatrzański',
      'Wadowicki',
      'Wielicki',
    ],
  },
  'Mazowieckie': {
    name: 'Mazowieckie',
    powiats: [
      'Warszawa',
      'Ostrołęka',
      'Płock',
      'Radom',
      'Siedlce',
      'Białobrzeski',
      'Ciechanowski',
      'Garwoliński',
      'Gostyniński',
      'Grodziski',
      'Grójecki',
      'Kozienicki',
      'Legionowski',
      'Lipski',
      'Łosicki',
      'Makówski',
      'Miński',
      'Mławski',
      'Nowodworski',
      'Ostrołęcki',
      'Ostrów Mazowiecka',
      'Otwocki',
      'Piaseczyński',
      'Płocki',
      'Płoński',
      'Pruszkowski',
      'Przysuski',
      'Pułtuski',
      'Radomski',
      'Siedlecki',
      'Sierpecki',
      'Sochaczewski',
      'Sokołowski',
      'Szydłowiecki',
      'Warszawski Zachodni',
      'Węgrowski',
      'Wołomiński',
      'Wyszkowski',
      'Żuromiński',
      'Żyrardowski',
    ],
  },
  'Opolskie': {
    name: 'Opolskie',
    powiats: [
      'Opole',
      'Brzeg',
      'Kędzierzyńsko-Kozielski',
      'Kluczborski',
      'Krapkowicki',
      'Namysłowski',
      'Nyski',
      'Oleski',
      'Opolski',
      'Prudnicki',
      'Strzelecki',
    ],
  },
  'Podkarpackie': {
    name: 'Podkarpackie',
    powiats: [
      'Rzeszów',
      'Krosno',
      'Przemyśl',
      'Tarnobrzeg',
      'Bieszczadzki',
      'Brzozowski',
      'Dębicki',
      'Jarosławski',
      'Jasielski',
      'Kolbuszowski',
      'Krośnieński',
      'Leski',
      'Leżajski',
      'Lubaczowski',
      'Łańcucki',
      'Mielecki',
      'Niżański',
      'Przemyski',
      'Przeworski',
      'Ropczycko-Sędziszowski',
      'Rzeszowski',
      'Sanocki',
      'Stalowowolski',
      'Strzyżowski',
      'Tarnobrzeski',
    ],
  },
  'Podlaskie': {
    name: 'Podlaskie',
    powiats: [
      'Białystok',
      'Łomża',
      'Suwałki',
      'Augustowski',
      'Białostocki',
      'Bielski',
      'Grajewski',
      'Hajnowski',
      'Kolneński',
      'Łomżyński',
      'Moniecki',
      'Sejneński',
      'Siemiatycki',
      'Sokólski',
      'Suwalski',
      'Wysokomazowiecki',
      'Zambrowski',
    ],
  },
  'Pomorskie': {
    name: 'Pomorskie',
    powiats: [
      'Gdańsk',
      'Gdynia',
      'Słupsk',
      'Sopot',
      'Bytowski',
      'Chojnicki',
      'Człuchowski',
      'Gdański',
      'Kartuski',
      'Kościerski',
      'Kwidzyński',
      'Lęborski',
      'Malborski',
      'Nowodworski',
      'Pucki',
      'Słupski',
      'Starogardzki',
      'Sztumski',
      'Tczewski',
      'Wejherowski',
    ],
  },
  'Śląskie': {
    name: 'Śląskie',
    powiats: [
      'Katowice',
      'Bielsko-Biała',
      'Bytom',
      'Chorzów',
      'Częstochowa',
      'Dąbrowa Górnicza',
      'Gliwice',
      'Jastrzębie-Zdrój',
      'Jaworzno',
      'Mysłowice',
      'Piekary Śląskie',
      'Ruda Śląska',
      'Rybnik',
      'Siemianowice Śląskie',
      'Sosnowiec',
      'Świętochłowice',
      'Tychy',
      'Zabrze',
      'Żory',
      'Będziński',
      'Bielski',
      'Cieszyński',
      'Częstochowski',
      'Gliwicki',
      'Kłobucki',
      'Lubliniecki',
      'Mikołowski',
      'Myszkowski',
      'Pszczyński',
      'Raciborski',
      'Rybnicki',
      'Tarnogórski',
      'Wodzisławski',
      'Zawierciański',
      'Żywiecki',
    ],
  },
  'Świętokrzyskie': {
    name: 'Świętokrzyskie',
    powiats: [
      'Kielce',
      'Buski',
      'Jędrzejowski',
      'Kazimierski',
      'Kielecki',
      'Konecki',
      'Opatowski',
      'Ostrowiecki',
      'Pińczowski',
      'Sandomierski',
      'Skarżyski',
      'Starachowicki',
      'Staszowski',
      'Włoszczowski',
    ],
  },
  'Warmińsko-Mazurskie': {
    name: 'Warmińsko-Mazurskie',
    powiats: [
      'Olsztyn',
      'Elbląg',
      'Bartoszycki',
      'Braniewski',
      'Działdowski',
      'Elbląski',
      'Ełcki',
      'Giżycki',
      'Gołdapski',
      'Iławski',
      'Kętrzyński',
      'Lidzbarski',
      'Mrągowski',
      'Nidzicki',
      'Nowomiejski',
      'Olecki',
      'Olsztyński',
      'Ostródzki',
      'Piski',
      'Szczycieński',
      'Węgorzewski',
    ],
  },
  'Wielkopolskie': {
    name: 'Wielkopolskie',
    powiats: [
      'Poznań',
      'Kalisz',
      'Konin',
      'Leszno',
      'Chodzieski',
      'Czarnkowsko-Trzcianecki',
      'Gnieźnieński',
      'Gostyński',
      'Grodziski',
      'Jarociński',
      'Kaliski',
      'Kępiński',
      'Kolski',
      'Koniński',
      'Kościanski',
      'Krotoszyński',
      'Leszczyński',
      'Międzychodzki',
      'Nowotomyski',
      'Obornicki',
      'Ostrowski',
      'Ostrzeszowski',
      'Pilski',
      'Pleszewski',
      'Poznański',
      'Rawicki',
      'Słupecki',
      'Szamotulski',
      'Średzki',
      'Śremski',
      'Turecki',
      'Wągrowiecki',
      'Wolsztyński',
      'Wrzesiński',
      'Złotowski',
    ],
  },
  'Zachodniopomorskie': {
    name: 'Zachodniopomorskie',
    powiats: [
      'Szczecin',
      'Koszalin',
      'Świnoujście',
      'Białogardzki',
      'Choszczeński',
      'Drawski',
      'Goleniowski',
      'Gryficki',
      'Gryfiński',
      'Kamieński',
      'Kołobrzeski',
      'Koszaliński',
      'Łobeski',
      'Myśliborski',
      'Policki',
      'Pyrzycki',
      'Sławieński',
      'Stargardzki',
      'Szczecinecki',
      'Świdwiński',
      'Wałewski',
    ],
  },
};

/**
 * Get list of all voivodeship names.
 */
export function getVoivodeshipNames(): string[] {
  return Object.keys(VOIVODESHIPS);
}

/**
 * Get powiats for a given voivodeship.
 */
export function getPowiatsForVoivodeship(voivodeship: string): string[] {
  return VOIVODESHIPS[voivodeship]?.powiats || [];
}

/**
 * Check if a voivodeship exists.
 */
export function isValidVoivodeship(voivodeship: string): boolean {
  return voivodeship in VOIVODESHIPS;
}

/**
 * Check if a poviat exists in a given voivodeship.
 */
export function isValidPoviat(voivodeship: string, poviat: string): boolean {
  const powiats = getPowiatsForVoivodeship(voivodeship);
  return powiats.includes(poviat);
}

