-- =====================================================================
-- migration:    create_core_schema
-- filename:     20251031120000_create_core_schema.sql
-- purpose:      utworzenie typów enum, tabel (profiles, announcements,
--               comments, reports), indeksów, rls oraz polityk bezpieczeństwa
--               z rozdzieleniem na role supabase (anon, authenticated).
--               dodatkowo: trigger automatycznego tworzenia profilu
--               po rejestracji użytkownika w auth.users oraz bezpieczne
--               rpc do pobierania telefonu autora ogłoszenia.
--
-- notes:
--  - wszystkie polecenia w lowercase
--  - każda nowa tabela ma włączone rls
--  - polityki są granularne: osobne dla select/insert/update/delete
--    i osobne dla ról 'anon' oraz 'authenticated'
--  - brak polityk rls na widokach (postgres nie wspiera rls na view)
--  - ochrona phone_number przez uprawnienia kolumnowe (revoke/grant)
--  - uważaj na destrukcyjne komendy przy modyfikacjach w przyszłości
-- =====================================================================

-- bezpieczeństwo i narzędzia
set check_function_bodies = off;

-- uuid generator dla announcements.id
create extension if not exists pgcrypto with schema public;

-- =====================================================================
-- 1) typy niestandardowe (enum)
-- =====================================================================

create type announcement_type as enum ('lost', 'found');
create type announcement_status as enum ('active', 'resolved');
create type animal_species as enum ('dog', 'cat');
create type animal_size as enum ('small', 'medium', 'large');
create type animal_age_range as enum ('young', 'adult', 'senior');

-- =====================================================================
-- 2) funkcje pomocnicze
-- =====================================================================

-- 2.1) trigger do uaktualniania kolumny updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 2.2) trigger tworzący wpis w public.profiles po rejestracji w auth.users
--      używa security definer, aby działał z poziomu triggera na auth.users
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  -- utwórz profil z tym samym id; username domyślnie z emaila przed '@'
  -- new.id i new.email pochodzą z auth.users (tabela na której jest trigger)
  insert into public.profiles (id, username, created_at)
  values (new.id, coalesce(split_part(new.email, '@', 1), encode(gen_random_bytes(6), 'hex')), now())
  on conflict (id) do nothing;

  return new;
end;
$$;

-- =====================================================================
-- 3) tabele
-- =====================================================================

-- 3.1) profiles: publiczne dane użytkownika powiązane z auth.users
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  phone_number text, -- wrażliwe dane kontaktowe (udostępniane wyłącznie przez rpc)
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3.2) announcements: ogłoszenia o zwierzętach
create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,

  type announcement_type not null,
  status announcement_status not null default 'active',

  voivodeship text not null,
  poviat text not null,
  location_details text,
  event_date date not null,

  species animal_species not null,
  image_url text not null,

  size animal_size,
  color text,
  age_range animal_age_range,
  description text,
  special_marks text,

  is_aggressive boolean not null default false,
  is_fearful boolean not null default false,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3.3) comments: komentarze do ogłoszeń
create table public.comments (
  id bigint generated by default as identity primary key,
  announcement_id uuid not null references public.announcements(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  is_sighting boolean not null default false,
  created_at timestamptz default now()
);

-- 3.4) reports: zgłoszenia nadużyć do ogłoszeń
create table public.reports (
  id bigint generated by default as identity primary key,
  announcement_id uuid not null references public.announcements(id) on delete cascade,
  reporting_user_id uuid not null references public.profiles(id) on delete cascade,
  reason text,
  created_at timestamptz default now(),
  unique (announcement_id, reporting_user_id)
);

-- =====================================================================
-- 4) triggery updated_at
-- =====================================================================

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_announcements_updated_at
before update on public.announcements
for each row execute function public.set_updated_at();

-- =====================================================================
-- 5) indeksy
-- =====================================================================

-- 5.1) announcements – filtrowanie
create index idx_announcements_location on public.announcements (voivodeship, poviat);
create index idx_announcements_species on public.announcements (species);
create index idx_announcements_status on public.announcements (status);
create index idx_announcements_size on public.announcements (size);
create index idx_announcements_age_range on public.announcements (age_range);
create index idx_announcements_color on public.announcements (color);
create index idx_announcements_event_date on public.announcements (event_date);

-- 5.2) klucze obce – wydajne joiny
create index idx_announcements_author_id on public.announcements (author_id);
create index idx_comments_announcement_id on public.comments (announcement_id);
create index idx_comments_author_id on public.comments (author_id);
create index idx_reports_announcement_id on public.reports (announcement_id);
create index idx_reports_reporting_user_id on public.reports (reporting_user_id);

-- =====================================================================
-- 6) rls + granularne polityki (anon vs authenticated)
--     uwaga: role odróżniamy przez predykat z auth.role()
-- =====================================================================

-- 6.1) profiles
alter table public.profiles enable row level security;

-- select: anon zablokowany na tabeli (by nie wyciekł phone_number przez select *)
-- publiczny odczyt zapewnia widok profiles_public
create policy profiles_select_anon_block
  on public.profiles for select
  using (auth.role() = 'anon' and false);

create policy profiles_select_authenticated
  on public.profiles for select
  using (auth.role() = 'authenticated' and true);

-- update: tylko właściciel (authenticated); anon zablokowany
create policy profiles_update_authenticated_self
  on public.profiles for update
  using (auth.role() = 'authenticated' and auth.uid() = id)
  with check (auth.role() = 'authenticated' and auth.uid() = id);

create policy profiles_update_anon_block
  on public.profiles for update
  using (auth.role() = 'anon' and false)
  with check (false);

-- delete: tylko właściciel (authenticated); anon zablokowany
create policy profiles_delete_authenticated_self
  on public.profiles for delete
  using (auth.role() = 'authenticated' and auth.uid() = id);

create policy profiles_delete_anon_block
  on public.profiles for delete
  using (auth.role() = 'anon' and false);

-- insert: pozwól funkcji SECURITY DEFINER na tworzenie profili przez trigger
-- funkcja handle_new_user używa SECURITY DEFINER, więc działa jako postgres
-- i może wstawiać rekordy dzięki tej polityce
create policy profiles_insert_trigger
  on public.profiles for insert
  with check (true);

-- ochrona numeru telefonu uprawnieniami kolumnowymi:
-- odbierz select do kolumny phone_number obu rolom aplikacyjnym.
revoke select (phone_number) on public.profiles from anon, authenticated;

-- (opcjonalnie) jawnie przyznaj select do pozostałych kolumn
grant select (id, username, created_at, updated_at) on public.profiles to anon, authenticated;

-- 6.2) announcements
alter table public.announcements enable row level security;

-- select: publiczny (osobno dla ról)
create policy announcements_select_anon
  on public.announcements for select
  using (auth.role() = 'anon' and true);

create policy announcements_select_authenticated
  on public.announcements for select
  using (auth.role() = 'authenticated' and true);

-- insert: tylko authenticated i tylko we własnym imieniu
create policy announcements_insert_authenticated
  on public.announcements for insert
  with check (auth.role() = 'authenticated' and auth.uid() = author_id);

create policy announcements_insert_anon_block
  on public.announcements for insert
  with check (auth.role() = 'anon' and false);

-- update: tylko autor (authenticated); anon zablokowany
create policy announcements_update_authenticated_self
  on public.announcements for update
  using (auth.role() = 'authenticated' and auth.uid() = author_id)
  with check (auth.role() = 'authenticated' and auth.uid() = author_id);

create policy announcements_update_anon_block
  on public.announcements for update
  using (auth.role() = 'anon' and false)
  with check (false);

-- delete: tylko autor (authenticated); anon zablokowany
create policy announcements_delete_authenticated_self
  on public.announcements for delete
  using (auth.role() = 'authenticated' and auth.uid() = author_id);

create policy announcements_delete_anon_block
  on public.announcements for delete
  using (auth.role() = 'anon' and false);

-- 6.3) comments
alter table public.comments enable row level security;

-- select: publiczny
create policy comments_select_anon
  on public.comments for select
  using (auth.role() = 'anon' and true);

create policy comments_select_authenticated
  on public.comments for select
  using (auth.role() = 'authenticated' and true);

-- insert: tylko authenticated i tylko we własnym imieniu
create policy comments_insert_authenticated
  on public.comments for insert
  with check (auth.role() = 'authenticated' and auth.uid() = author_id);

create policy comments_insert_anon_block
  on public.comments for insert
  with check (auth.role() = 'anon' and false);

-- update: tylko autor (authenticated); anon zablokowany
create policy comments_update_authenticated_self
  on public.comments for update
  using (auth.role() = 'authenticated' and auth.uid() = author_id)
  with check (auth.role() = 'authenticated' and auth.uid() = author_id);

create policy comments_update_anon_block
  on public.comments for update
  using (auth.role() = 'anon' and false)
  with check (false);

-- delete: tylko autor (authenticated); anon zablokowany
create policy comments_delete_authenticated_self
  on public.comments for delete
  using (auth.role() = 'authenticated' and auth.uid() = author_id);

create policy comments_delete_anon_block
  on public.comments for delete
  using (auth.role() = 'anon' and false);

-- 6.4) reports
alter table public.reports enable row level security;

-- select: blokada publicznego odczytu (obie role)
create policy reports_select_anon_block
  on public.reports for select
  using (auth.role() = 'anon' and false);

create policy reports_select_authenticated_block
  on public.reports for select
  using (auth.role() = 'authenticated' and false);
-- uwaga: do wglądu przez serwis/admina używaj service_role (omija rls)

-- insert: tylko authenticated i tylko we własnym imieniu
create policy reports_insert_authenticated_self
  on public.reports for insert
  with check (auth.role() = 'authenticated' and auth.uid() = reporting_user_id);

create policy reports_insert_anon_block
  on public.reports for insert
  with check (auth.role() = 'anon' and false);

-- brak update/delete (domyślnie zablokowane) – w razie potrzeby dodać

-- =====================================================================
-- 7) rpc: bezpieczne pobieranie telefonu autora ogłoszenia
--     funkcja zwraca phone_number właściciela ogłoszenia; dostępna
--     tylko dla zalogowanych (sprawdzane w ciele funkcji).
-- =====================================================================

create or replace function public.get_contact_details(p_announcement_id uuid)
returns table (phone_number text)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'authenticated' then
    -- brak uprawnień dla niezalogowanych
    return;
  end if;

  return query
  select p.phone_number
  from public.announcements a
  join public.profiles p on p.id = a.author_id
  where a.id = p_announcement_id;
end;
$$;

-- (opcjonalne) możesz dodatkowo ograniczyć execute tej funkcji grantami.

-- =====================================================================
-- 8) trigger na auth.users (po utworzeniu tabele i funkcji)
-- =====================================================================

-- bezpiecznie usuń stary trigger (jeśli istnieje), a następnie utwórz nowy
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =====================================================================
-- 9) widok publiczny bez telefonu (brak rls na widokach)
--     widok służy tylko jako wygodny alias do bezpiecznych kolumn.
-- =====================================================================

drop view if exists public.profiles_public;
create view public.profiles_public as
select
  id,
  username,
  created_at
from public.profiles;

comment on view public.profiles_public is
  'publiczny widok profili użytkowników eksponujący tylko bezpieczne kolumny (bez phone_number).';

-- zwykłe uprawnienia (grant) na widok – rls jest egzekwowane na tabeli bazowej
grant select on public.profiles_public to anon, authenticated;

-- =====================================================================
-- koniec migracji
-- =====================================================================
